# Generated by Django 6.0.5 on 2026-08-23 23:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse1', models.CharField(max_length=180)),
                ('adresse2', models.CharField(blank=True, max_length=180)),
                ('ville', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('principale', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titre', models.CharField(max_length=120)),
                ('commentaire', models.TextField()),
                ('approuve', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_zendo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='zendo.categorie')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('attente', 'En attente'), ('confirmee', 'Confirmée'), ('preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='attente', max_length=20)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('livraison', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tps', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tvq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('note_client', models.TextField(blank=True)),
                ('adresse_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='zendo.adresse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type_remise', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant', 'Montant fixe')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_commande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField()),
                ('limite_utilisations', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('utilisations', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=160)),
                ('type_evenement', models.CharField(choices=[('tache', 'Tâche'), ('rendez_vous', 'Rendez-vous'), ('promotion', 'Promotion'), ('autre', 'Autre')], default='tache', max_length=20)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('termine', models.BooleanField(default=False)),
                ('assigne_a', models.ManyToManyField(blank=True, related_name='evenements_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, upload_to='factures/%Y/%m/')),
                ('envoyee', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='zendo.commande')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publiee', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_zendo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/%Y/%m/')),
                ('texte_alt', models.CharField(blank=True, max_length=180)),
                ('principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=70)),
                ('details_variante', models.CharField(blank=True, max_length=200)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('personnalisation', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='zendo.commande')),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('personnalisation', models.TextField(blank=True)),
                ('fichier_personnalisation', models.FileField(blank=True, upload_to='personnalisations/')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('transporteur', models.CharField(blank=True, max_length=100)),
                ('numero_suivi', models.CharField(blank=True, max_length=120)),
                ('url_suivi', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('preparation', 'Préparation'), ('expediee', 'Expédiée'), ('transit', 'En transit'), ('livree', 'Livrée'), ('retour', 'Retournée')], default='preparation', max_length=20)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('livraison_prevue', models.DateField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_livraison', to='zendo.commande')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('contenu', models.TextField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('vente', 'Vente'), ('retour', 'Retour'), ('ajustement', 'Ajustement'), ('perte', 'Perte')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('stock_apres', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('methode', models.CharField(choices=[('stripe', 'Carte bancaire'), ('paypal', 'PayPal'), ('interac', 'Interac'), ('lien', 'Lien de paiement'), ('manuel', 'Paiement manuel')], max_length=20)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('autorise', 'Autorisé'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_externe', models.CharField(blank=True, max_length=150)),
                ('lien_paiement', models.URLField(blank=True)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='zendo.commande')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier_zendo', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zendo.coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametresEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(default='Zendo Afrique', max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('devise', models.CharField(default='CAD', max_length=3)),
                ('taux_tps', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=6)),
                ('taux_tvq', models.DecimalField(decimal_places=3, default=Decimal('9.975'), max_digits=6)),
                ('seuil_stock_faible', models.PositiveIntegerField(default=5)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Paramètres de l’entreprise',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('vedette', models.BooleanField(default=False)),
                ('personnalisable', models.BooleanField(default=False)),
                ('delai_personnalisation', models.PositiveIntegerField(default=0, help_text='Nombre de jours')),
                ('poids_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='zendo.categorie')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('employe', 'Employé'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur')], default='client', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='profils/')),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('effectue', 'Effectué')], default='demande', max_length=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='zendo.paiement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('sujet', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cours', 'En cours'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes_zendo', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_zendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=70, unique=True)),
                ('taille', models.CharField(blank=True, max_length=40)),
                ('couleur', models.CharField(blank=True, max_length=60)),
                ('modele', models.CharField(blank=True, max_length=80)),
                ('supplement_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='beaute',
        ),
        migrations.DeleteModel(
            name='Boutique',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='hygiene',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='similar_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='zendo.panier'),
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zendo.produit'),
        ),
        migrations.AddField(
            model_name='favori',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dans_favoris', to='zendo.produit'),
        ),
        migrations.AddField(
            model_name='avis',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='zendo.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produits', to='zendo.tag'),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='zendo.ticketsupport'),
        ),
        migrations.AddField(
            model_name='varianteproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='zendo.produit'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='zendo.varianteproduit'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zendo.varianteproduit'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='variante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zendo.varianteproduit'),
        ),
        migrations.DeleteModel(
            name='Beaute',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Hygiene',
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(fields=('client', 'produit'), name='favori_unique'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('produit', 'client'), name='avis_unique'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'taille', 'couleur', 'modele'), name='variante_unique'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.UniqueConstraint(fields=('panier', 'variante', 'personnalisation'), name='ligne_panier_unique'),
        ),
    ]
