# Generated by Django 6.0.5 on 2026-09-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendo', '0002_adresse_avis_categorie_commande_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='derniere_relance_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='nombre_relances_paiement',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
