# Generated by Django 6.0.5 on 2026-09-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendo', '0003_commande_derniere_relance_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePersonnalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20, verbose_name='Type de client')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, verbose_name='Nom de l’entreprise')),
                ('telephone', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('code_postal', models.CharField(max_length=20, verbose_name='Code postal')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('couleur', models.CharField(blank=True, max_length=100, verbose_name='Couleur souhaitée')),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name='Taille(s)')),
                ('description', models.TextField(verbose_name='Description de la demande')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='personnalisation/%Y/%m/', verbose_name='Logo, image ou plan')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle demande'), ('traitement', 'En traitement'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de personnalisation',
                'verbose_name_plural': 'Demandes de personnalisation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
