# Generated by Django 6.0.5 on 2026-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendo', '0004_demandepersonnalisation_alter_categorie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='lien_paiement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
