# Generated by Django 6.0.5 on 2026-09-29 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendo', '0005_alter_paiement_lien_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='zendo.varianteproduit'),
        ),
    ]
